<?xml version="1.0" encoding="utf-8"?><Database Name="feedback_manager" Class="FeedbackManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VLADO\SQLEXPRESS;Initial Catalog=feedback_manager;Persist Security Info=True;User ID=FeedbackManager" SettingsObjectName="FM.Data.Access.Impl.LinqSql.Properties.Settings" SettingsPropertyName="feedback_managerConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FM_Feedback" Member="FM_Feedbacks">
    <Type Name="FM_Feedback" Id="ID1">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="game_session_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FM_Game_Session_FM_Feedback" Member="FM_Game_Session" ThisKey="game_session_id" OtherKey="id" Type="FM_Game_Session" IsForeignKey="true" />
      <Association Name="FM_User_FM_Feedback" Member="FM_User" ThisKey="user_id" OtherKey="id" Type="FM_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FM_Game" Member="FM_Games">
    <Type Name="FM_Game">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="FM_Game_FM_Game_Session" Member="FM_Game_Sessions" ThisKey="id" OtherKey="game_id" Type="FM_Game_Session" />
    </Type>
  </Table>
  <Table Name="dbo.FM_Game_Session" Member="FM_Game_Sessions">
    <Type Name="FM_Game_Session">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="game_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="session_identifier" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="FM_Game_Session_FM_Feedback" Member="FM_Feedbacks" ThisKey="id" OtherKey="game_session_id" Type="FM_Feedback" />
      <Association Name="FM_Game_FM_Game_Session" Member="FM_Game" ThisKey="game_id" OtherKey="id" Type="FM_Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FM_Role" Member="FM_Roles">
    <Type Name="FM_Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FM_Role_FM_User" Member="FM_Users" ThisKey="id" OtherKey="role_id" Type="FM_User" />
    </Type>
  </Table>
  <Table Name="dbo.FM_User" Member="FM_Users">
    <Type Name="FM_User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_login" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="user_password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FM_User_FM_Feedback" Member="FM_Feedbacks" ThisKey="id" OtherKey="user_id" Type="FM_Feedback" />
      <Association Name="FM_Role_FM_User" Member="FM_Role" ThisKey="role_id" OtherKey="id" Type="FM_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_insert_feedback" Method="sp_insert_feedback">
    <Parameter Name="rating" Type="System.Int32" DbType="Int" />
    <Parameter Name="user_login" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="session_identifier" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="comment" Type="System.String" DbType="NVarChar(500)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>